theme: minimal
title: Ryan Huang
affiliation: Undergraduate Student at the University of North Carolina at Chapel Hill
email: rhuang1@unc.edu
github_link: https://github.com/rhuang11
linkedin: https://www.linkedin.com/rhuang11
avatar: IMG_20220913_190630_723.jpg
favicon: https://lh3.googleusercontent.com/a/AEdFTp6C47c7YOpWEm_b4CN4OChwmVigJ_TVsQeernKgQA=s576-p-no
description:

